language: python
python:
  - "3.6"
# command to build
install:
  - pip3 install xlrd
script:
  # When cloning the repository, TravisCI uses `--shallow`, which implies
  # `--single-branch`. The deployment branch must be fetched explicitly from a
  # repository created in this way.
  - git fetch origin gh-pages
  - git checkout FETCH_HEAD -- data.csv
  - python3 build.py
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
  target-branch: gh-pages
